### ISSUE TITLE
onMount() is not called in version 4.7.1

### ISSUE THREAD

**Issue by neunygph** [marko-js/marko#946]
The onMount() event works fine for me in version 4.2.8 and below, but when I upgraded to version 4.7.1 it stopped working, the event never get called on both server and client side. When I switched back to version 4.2.8 it worked again meaning nothing is wrong with my code. I have something like the below code:

module.exports = {
    onInput(input) {
        console.log('on input')

    },
    onCreate(input) {
        console.log('on create')
    },
    onRender(out) {
        console.log('on render')
    },

    onMount() {
        console.log('on mount')
    },

    onUpdate() {

        }
    },
};

**Comment by austinkelleher** [comment]
@neunygph Thanks for opening this issue. This is definitely a bug. We will have a fix soon.

**Comment by hedav85** [comment]
I also updated my project from 4.6 to 4.7 and it seems that no js is called. In 4.6 everything working well.

**Comment by smulder** [comment]
Seeing this also

**Comment by austinkelleher** [comment]
Hey @smulder @hedav85 @neunygph. This issue should be fixed. You will need to upgrade `lasso`, `lasso-marko` and `marko` to the latest. Also delete your lasso `.cache` folders. Let me know if this issue goes away.

**Comment by hedav85** [comment]
@austinkelleher I've updated now to the latest version. For me its working now.

I found out that my problem is related to another issue. I opened a separate issue #949 for this.

**Comment by neunygph** [comment]
Thanks @austinkelleher

**Comment by wmarrujo** [comment]
This is still happening for me in 4.18.2.
Same setup, just a marko component file and no "on mount" being logged on server or browser. No other configuration options changed that I know of.

my setup:
node.js 12.3.1 with express 4.17.1
macOS 10.14.5
Safari 12.1.1 or Chrome 74
no bundler integration used

**Comment by DylanPiercey** [comment]
@wmarrujo the `onMount` lifecycle event is only fired in the browser code. For any of the browser side logic to be ran you need to send the JavaScript for the Marko template to the browser using a bundler like Lasso or Webpack. 

You can find some samples here:
[webpack](https://github.com/marko-js-samples/marko-webpack)
[lasso](https://github.com/marko-js-samples/marko-express)

**Comment by wmarrujo** [comment]
ah, ok. I didn't see that a bundler was required for that since everything else was working without one. thanks.
